export const CATEGORIZED_FEEDS = {
  'My External': {
    'N-O-D-E': 'https://n-o-d-e.net/rss/rss.xml',
    'apalrd': 'https://www.apalrd.net/index.xml',
    'mblog': '/tags/mblog/rss.xml',
  },
} as const;

export const ARCHIVED_FEEDS = {
  'Learning': {
    'The Decision Lab': 'https://thedecisionlab.com/feed/',
    'Ness Labs': 'https://nesslabs.com/feed',
    'Farnam Street': 'https://fs.blog/feed/',
    'The Sunday Wisdom': 'https://coffeeandjunk.substack.com/feed',
    'Commonplace - The Commoncog Blog': 'https://commoncog.com/blog/rss/',
    'Scott H Young': 'https://feeds.feedburner.com/scotthyoung/HAHx',
    'Big Think': 'https://feeds.feedburner.com/bigthink/main',
  },
  'Startup': {
    'Steve Blank': 'http://steveblank.com/feed/',
    'The singularity is nearer': 'https://geohot.github.io/blog/feed.xml',
    'Hacker News': 'http://news.ycombinator.com/rss',
    'Guy Kawasaki': 'http://guykawasaki.com/feed/',
    'Essays - Benedict Evans': 'http://ben-evans.com/benedictevans?format=rss',
    'First Round Review': 'http://firstround.com/review/feed.xml',
    'Sam Altman': 'http://blog.samaltman.com/posts.atom',
    'Andrew Chen': 'http://andrewchen.co/feed/',
    'Both Sides of the Table - Medium': 'https://bothsidesofthetable.com/feed',
    'OnStartups': 'http://feed.onstartups.com/onstartups',
    'The Black Box of Product Management - Medium': 'https://medium.com/feed/the-black-box-of-product-management',
    'Product Life': 'https://productlife.to/feed',
    'Irrational Exuberance': 'https://lethain.com/feeds/',
  },
  'Tech News': {
    'SlashGear': 'http://feeds.slashgear.com/slashgear',
    'VentureBeat': 'http://venturebeat.com/feed/',
    'The Verge': 'http://www.theverge.com/rss/full.xml',
    'Engadget': 'http://www.engadget.com/rss-full.xml',
    'Tech in Asia': 'https://feeds2.feedburner.com/PennOlson',
    'TechCrunch': 'https://techcrunch.com/feed/',
    'Fast Company': 'http://feeds.feedburner.com/fastcompany/headlines',
    'Startups – TechCrunch': 'https://techcrunch.com/startups/feed/',
    'Forbes - Leadership': 'https://www.forbes.com/leadership/feed/',
    'Forbes - Entrepreneurs': 'http://www.forbes.com/entrepreneurs/index.xml',
  },
  'Products & Ideas': {
    'Product Hunt': 'http://www.producthunt.com/feed',
    'Hacker News: Show HN': 'http://hnrss.org/show',
    'Hacker News: Launches': 'https://hnrss.org/launches',
    'Sachin Rekhi\'s Blog': 'http://feeds.feedburner.com/sachinrekhiblog',
  },
  'Engineering blogs': {
    'The Airtable Engineering Blog': 'https://medium.com/feed/airtable-eng',
    'Medium Engineering': 'https://medium.com/feed/medium-eng',
    'PayPal Technology Blog': 'https://medium.com/feed/paypal-engineering',
    'Pinterest Engineering': 'https://medium.com/feed/pinterest-engineering',
    'Grab Tech': 'https://engineering.grab.com/feed.xml',
    'Slack Engineering': 'https://slack.engineering/feed',
    'GitHub Engineering': 'http://githubengineering.com/atom.xml',
    'Atlassian Developer Blog': 'https://developer.atlassian.com/blog/feed.xml',
    'Facebook Engineering': 'https://engineering.fb.com/feed/',
    'eBay Tech Blog': 'http://www.ebaytechblog.com/feed/',
    'Spotify Engineering': 'https://engineering.atspotify.com/feed/',
    'Twitter Engineering': 'https://blog.twitter.com/engineering/en_us/blog.rss',
    'Stripe Blog': 'https://stripe.com/blog/feed.rss',
    'Instagram Engineering': 'https://instagram-engineering.com/feed',
    'Cloudflare Blog': 'https://blog.cloudflare.com/rss/',
    'Asana Engineering': 'https://blog.asana.com/category/eng/feed/',
    'Canva Engineering': 'https://engineering.canva.com/rss',
    'Airbnb Tech': 'https://medium.com/feed/airbnb-engineering',
    'Dropbox Tech': 'https://dropbox.tech/feed',
    'Web Browser Engineering': 'https://browser.engineering/rss.xml',
    'Mind the Product': 'https://www.mindtheproduct.com/feed/',
    'Julia Evans': 'https://jvns.ca/atom.xml',
    'Martin Kleppmann': 'https://feeds.feedburner.com/martinkl?format=xml',
    'Dan Abramov': 'https://overreacted.io/rss.xml',
    'Dan Luu': 'https://danluu.com/atom.xml',
    'Shopify Engineering': 'https://shopifyengineering.myshopify.com/blogs/engineering.atom',
    'Josh Comeau': 'https://joshwcomeau.com/rss.xml',
    'Uber Engineering': 'https://eng.uber.com/feed/',
    'Stripe CTO blog': 'https://blog.singleton.io/index.xml',
    'Sophie Alpert': 'https://sophiebits.com/atom.xml',
    'Amjad Masad': 'https://amasad.me/rss',
    'Signal Blog': 'https://signal.org/blog/rss.xml',
    'Joel on Software': 'https://www.joelonsoftware.com/feed/',
    'The Pragmatic Engineer': 'https://blog.pragmaticengineer.com/rss/',
    'Nvidia Developer Blog': 'https://developer.nvidia.com/blog/feed',
  },
  'Machine Learning': {
    'ML@CMU': 'https://blog.ml.cmu.edu/feed/',
    'DeepMind': 'https://deepmind.com/blog/feed/basic/',
    'Jay Alammar': 'https://jalammar.github.io/feed.xml',
    'Distill': 'http://distill.pub/rss.xml',
    'Lil\'Log': 'https://lilianweng.github.io/lil-log/feed.xml',
    'MIT News - AI': 'http://news.mit.edu/rss/topic/artificial-intelligence2',
    'Sebastian Ruder': 'http://ruder.io/rss/index.rss',
    'BAIR': 'http://bair.berkeley.edu/blog/feed.xml',
    'DeepLearningAI': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCcIXc5mJsHVYTZR1maL5l9w',
    'Eric Jang': 'https://evjang.com/feed',
    'OpenAI': 'https://openai.com/news/engineering/rss.xml',
    'The Gradient': 'https://thegradient.pub/rss/',
    'Magenta': 'http://magenta.tensorflow.org/feed.xml',
    'NLP News': 'http://newsletter.ruder.io/?format=rss',
    'Google AI Blog': 'http://googleresearch.blogspot.com/atom.xml',
    'Towards Data Science': 'https://towardsdatascience.com/feed',
    'Unite.AI': 'https://www.unite.ai/feed/',
    'Grammarly Blog': 'https://www.grammarly.com/blog/feed/',
    'Amazon Science': 'https://www.amazon.science/index.rss',
    'r/MachineLearning': 'http://www.reddit.com/r/MachineLearning/.rss',
    'Yannic Kilcher': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew',
    'Two Minute Papers': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg',
    'PyTorch': 'https://pytorch.org/feed',
  },
  'Design': {
    'UX Planet': 'https://uxplanet.org/feed',
    'Nielsen Norman Group': 'https://www.nngroup.com/feed/rss/',
    'UX Movement': 'http://feeds.feedburner.com/uxmovement',
    'Inside Design': 'http://blog.invisionapp.com/feed/',
    'UXmatters': 'https://uxmatters.com/index.xml',
    'Smashing Magazine': 'https://www.smashingmagazine.com/feed/',
    'UX Collective': 'https://uxdesign.cc/feed',
    'Airbnb Design': 'http://airbnb.design/feed/',
    'web.dev': 'https://web.dev/feed.xml',
    'Slack Design': 'https://slack.design/feed/',
    'CSS-Tricks': 'https://feeds.feedburner.com/CssTricks',
    'IxDF UX Daily': 'https://interaction-design.org/rss/site_news.xml',
  },
  'Psychology': {
    'PsyBlog': 'http://feeds.feedburner.com/PsychologyBlog',
    'Psychology Blog': 'http://www.all-about-psychology.com/psychology.xml',
    'Psychology Headlines': 'http://www.socialpsychology.org/headlines.rss',
    'Nautilus': 'https://nautil.us/rss/all',
    'Freakonomics': 'http://freakonomics.blogs.nytimes.com/feed/',
    'Psychology Today': 'https://www.psychologytoday.com/intl/rss.xml',
  },
  'Neuroscience': {
    'Neuroscience News': 'http://neurosciencenews.com/feed/',
    'ScienceDaily Neuroscience': 'https://sciencedaily.com/rss/mind_brain/neuroscience.xml',
    'SharpBrains': 'http://www.sharpbrains.com/feed/',
  },
  'Science': {
    'Quanta Magazine': 'http://www.quantamagazine.org/feed/',
    'Nature': 'http://www.nature.com/nature/current_issue/rss',
    'MIT News - STS': 'https://news.mit.edu/rss/topic/science-technology-and-society',
    'MIT News Research': 'https://news.mit.edu/rss/research',
    'ScienceAlert': 'https://www.sciencealert.com/rss',
    'Singularity Hub': 'https://singularityhub.com/feed/',
    'Lesics': 'https://www.youtube.com/feeds/videos.xml?channel_id=UCqZQJ4600a9wIfMPbYc60OQ',
  },
  'Marketing': {
    'Moz': 'http://feeds.feedburner.com/seomoz',
    'Content Marketing Institute': 'http://feeds.feedburner.com/cmi-content-marketing',
    'Neil Patel': 'http://feeds.feedburner.com/KISSmetrics',
    'MarketingProfs': 'http://rss.marketingprofs.com/marketingprofs/daily',
    'Marketo': 'http://feeds.feedburner.com/modernb2bmarketing',
    'Quick Sprout': 'http://www.quicksprout.com/feed/',
    'Social Media Examiner': 'http://www.socialmediaexaminer.com/feed/',
    'John Egan': 'http://jwegan.com/feed/rss/',
    'Convince and Convert': 'http://www.convinceandconvert.com/feed/',
    'Hubspot': 'http://blog.hubspot.com/CMS/UI/Modules/BizBlogger/rss.aspx?tabid=6307&moduleid=8441&maxcount=25',
    'Seth Godin': 'http://sethgodin.typepad.com/seths_blog/atom.xml',
    'Backlinko': 'http://backlinko.com/feed',
  },
  'Others': {
    'TED Talks Daily': 'http://feeds.feedburner.com/tedtalks_video',
    'HBR.org': 'http://feeds.harvardbusiness.org/harvardbusiness/',
  },
} as const;

export const FEED_COLORS: Record<string, string> = {
  'N-O-D-E': 'bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300',
  'apalrd': 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300',
  'mblog': 'bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300',
};

export const CATEGORY_COLORS: Record<string, string> = {
  'My External': 'text-blue-600 dark:text-blue-400',
  'Learning': 'text-purple-600 dark:text-purple-400',
  'Startup': 'text-green-600 dark:text-green-400',
  'Tech News': 'text-red-600 dark:text-red-400',
  'Products & Ideas': 'text-yellow-600 dark:text-yellow-400',
  'Engineering blogs': 'text-cyan-600 dark:text-cyan-400',
  'Machine Learning': 'text-pink-600 dark:text-pink-400',
  'Design': 'text-indigo-600 dark:text-indigo-400',
  'Psychology': 'text-orange-600 dark:text-orange-400',
  'Neuroscience': 'text-teal-600 dark:text-teal-400',
  'Science': 'text-lime-600 dark:text-lime-400',
  'Marketing': 'text-rose-600 dark:text-rose-400',
  'Others': 'text-gray-600 dark:text-gray-400',
};
